on:
  push:
    branches:
      - main

name: Test with Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v7

    - uses: pnpm/action-setup@v6

    - name: Use Node.js 22.x
      uses: actions/setup-node@v7
      with:
        node-version: 22.x
        cache: pnpm

    - name: pnpm install, pnpm test:coverage
      run: |
        pnpm install --frozen-lockfile
        echo repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }} > .coveralls.yml
        pnpm test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
